[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
aarch64-cpu = "9.3.1"
panic-halt = "0.2.0"
tock-registers = "0.8.1"


[[bin]]
name = "kernel8"
path = "src/main.rs"
test = false
bench = false
